GET  http://127.0.0.1:8000/train
Content-Type: application/json
################################
POST  https://ultimate-chatbot.tk:8080/
Content-Type: application/json

{
    "question": "quên đóng học phí"
}
#######################
GET https://chatbot-capstone1.herokuapp.com/train
Content-Type: application/json